// Auto-reconstructed: mars_rfspi.h
// Generated by assemble.py — do not edit manually
#pragma once
#include <stdint.h>
#include <stdbool.h>

// conf=100%  compile=ok  // Sets bit 10 (0x400) of register at 0x4001B00C (likely RF SPI control).
void ah_rfspi_clear_pd(void);

// conf=95%  compile=ok  // Disables RF SPI interface by clearing bits 8 and 9 in register 0, clears lower 3 bits in register 1, then calls ah_rfspi_get_pd.
void ah_rfspi_close(void);

// conf=100%  compile=ok  // Reads bit 10 (0x400) from register at offset 0xC from base 0x4001B000.
uint32_t ah_rfspi_get_pd(void);

// conf=70%  compile=ok  // Initializes RF SPI controller with config based on arg0, performs unknown function calls via passed function pointers, compares APB clock with scaled arg1, and calls unknown function with comparison result.
int ah_rfspi_open(int arg0, uint32_t arg1, uint32_t arg2);

// conf=95%  compile=ok  // Reads a 16-bit value from RF SPI register at address reg_addr, using hardware registers at base 0x4001B000.
uint16_t ah_rfspi_read(uint16_t reg_addr);

// conf=95%  compile=ok  // Sets RF SPI clock divider by clearing bits 16-23, computing divider from APB clock and base 2 MHz, then writing divider-1 into bits 16-23.
int ah_rfspi_set_clk(uint8_t clk_div);

// conf=95%  compile=ok  // Sets RX delay bits (24-26) in a hardware register at 0x4001B000, returns 0 on success, -1 if delay >= 8.
int32_t ah_rfspi_set_rx_dly(uint32_t delay);

// conf=100%  compile=ok  // Sets RF SPI trigger mode by clearing bit 1 then ORing shifted mode into register at 0x4001B000.
int ah_rfspi_set_trig_mode(uint32_t mode);

// conf=95%  compile=ok  // Writes a 32-bit data word to RF SPI register at given 16-bit address, with hardware handshake and timeout.
void ah_rfspi_write(uint16_t addr, uint32_t data);

// conf=95%  compile=ok  // Writes addr/data via ah_rfspi_write, then reads back result via ah_rfspi_read.
uint16_t ah_rfspi_write_and_read(uint32_t addr, uint32_t data);

// conf=95%  compile=ok  // Configures RF SPI pin multiplexing and direction based on mode (1=alt func 3, 2=alt func 4, 3=alt func 1, else GPIO input).
void rfspi_pin_func(uint32_t mode);
